version: 0.2

phases:
  install:
    commands:
      - printenv
      - npm install -g ember-cli@latest
      - npm install
  build:
    commands:
      - ember b --environment=production
artifacts:
  base-directory: dist
  files:
    - **/*
